### ISSUE TITLE
supported_os add big sur?

### ISSUE THREAD

**Issue by ABrdfd** [munkireport/supported_os#21]
Greetings, after updating Munkireport to 5.6.6 and composer dependencies, supported_os still only lists Highest Supported OS of 10.15.5 for all devices, even those currently on 11.2.3

**Comment by flammable** [comment]
5.6.5 is the latest version - you probably don't want to be running 5.6.6 yet.

**Comment by ABrdfd** [comment]
Boo.  I just followed the upgrade procedures as listed in the munkireport wiki.  Think that's causing the issue?

**Comment by bochoven** [comment]
The git version is 5.6.6 due to a mistake on my part. It’s nit causing the issue

**Comment by tuxudo** [comment]
The module doesn't have to be updated for each new release. You can update the latest supported versions by going to the Admin tab, then Supported OS and clicking Refresh OS Version Data. That will pull down the latest information from GitHub.

**Comment by ABrdfd** [comment]
Thank you for the instruction.  I did follow it and can confirm that Highest Supported OS still maxes out at 10.15.5 for all devices.

**Comment by tuxudo** [comment]
What is the data source listed at OS Version Data Source after you click the button to update the data?

**Comment by ABrdfd** [comment]
The data source is Github

**Comment by tuxudo** [comment]
What is the data source after you click the Update OS Version Data?

**Comment by ABrdfd** [comment]
It says Data Updated from Github, as a link to https://github.com/munkireport/supported_os/blob/master/supported_os_data.yml, I imagine as expected.

**Comment by tuxudo** [comment]
Good, that sounds like it's working. The `Current OS` field should then change to 11.2.3 after you've clicked that button and it processes the latest supported OS versions

**Comment by ABrdfd** [comment]
Interestingly, only one device in our fleet shows 11+ in the Highest Supported OS field, as it's the only device we purchased that shipped with 11.  Even devices which are currently on 11 still show Highest Supported OS of 10.15.5.  This feels nit-picky but we were trying to make an assessment for planning purposes and this tool is not helping at present because of this.  I have included a screen shot.
<img width="1003" alt="Screen Shot 2021-04-15 at 10 23 59 AM" src="https://user-images.githubusercontent.com/12547332/114885740-f42ab800-9dd4-11eb-827c-bf83b419599e.png">

**Comment by tuxudo** [comment]
Machines will only update their highest supported OS when they check in and no more than once every 7 days. You can manually refresh all the machines by clicking the Process All Machines button on the Supported OS admin page. 

Example, if one of those MacBookPro15,4 machines hasn't been turned on since January, it'll show the latest version as being 10.15.5 because that's the latest version the MunkiReport server knew about when that Macbook Pro last checked in.

**Comment by ABrdfd** [comment]
Brilliant, I apologize for not understanding the full functionality of this tool.  Thanks for your help.

**Comment by tuxudo** [comment]
Happy to have helped :) I'm going to update the readme to make it more clear
