### ISSUE TITLE
Current OS not updating

### ISSUE THREAD

**Issue by cemkoker** [munkireport/supported_os#28]
I have a weird issue; current OS is not updating.
I have Macmini81; tried manually editing the supported_os_data.yml and add a line for MacMini highest supported os ('81': '0')
then on the dashboard going to Admin>Supported OS>Process all machines

I don't see update in the dashboard for the current os; tried changing CHECK variable to 60 seconds, no luck.
but running sw_vers -productVersion does give me the correct version

running Munki 5.6.4

Any idea why ?

**Comment by tuxudo** [comment]
The yml file is only used for determining the `Shipping OS` and `Most current OS released by Apple` The `Current OS` field is controlled by the client and will only update once every week. 

Example: If the Mac Mini is running 12.2.1 on Monday and you update it on Wednesday to run 12.3, MunkiReport will not show 12.3 as the "Current OS" until Monday. 

You can force it to update by running `sudo rm /usr/local/munkireport/scripts/cache/supported_os.plist; sudo /usr/local/munkireport/munkireport-runner`
