### ISSUE TITLE
Bug - MacPro5,1 can't run 10.14 (mostly)

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/supported_os#9]
The MacPro5,1 can only go up to 10.13 with the shipped ATI Radeon HD 5770 or 5870. The card must be upgraded for 10.14 support (Metal)

This is documented here https://support.apple.com/en-us/HT208898

**Comment by kevinmcox** [comment]
This was addressed with #8 last week.

**Comment by kevinmcox** [comment]
What is your thought on how to handle it? Apple officially says that the MacPro5,1 can run Mojave and that is what most other third party sites report as well. Should we stick with that official position or deviate from it?

Last week in #8 we discussed sticking with official Apple recommendations for the module, even if other things are possible. I doubt there is an easy way to add an asterisk to the module listings.

What do you think @tuxudo?

**Comment by ofirgalcon** [comment]
I guess technically the computer can run 10.14 with a minor modification.

**Comment by kevinmcox** [comment]
Right, probably simplest to just stick with Apple's official stated position. I imagine anyone with these old computers still in use, like me, already know the caveats.
